remote_theme: daattali/beautiful-jekyll@6.0.1
title: Movies in time
author: Haoyu Wen, Florian Delavy, Robin Patriarca, Leo Sperber

description: Our project website

navbar-links:
  datasets: "datasets"

social-network-links:
email: "leo.sperber@epfl.ch"

example.md
exclude:
  README.md
  
