remote_theme: daattali/beautiful-jekyll@6.0.1
title: Movies in time
author: Haoyu Wen, Florian Delavy, Robin Patriarca, Leo Sperber

description: Our project website

cover-img: /assets/img/time.jpg

navbar-links:
  example: "example"

social-network-links:
email: "leo.sperber@epfl.ch"

exclude:
  README.md
