remote_theme: daattali/beautiful-jekyll@6.0.1
title: Movies in time
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example.md
